Repository moCOMOco-main4/frontend, pull requests merged in 2025-05, with the labels that each got.

#40 #26 feat: 소셜로그인 기능 구현 (백엔드 API 서버 연결 전)
  .gitignore
  next-env.d.ts
  src/app/auth/callback/kakao/page.tsx
  src/app/auth/callback/naver/page.tsx
  src/app/auth/login/page.tsx
  src/auth/login/page.tsx
  src/store/useAuthStore.ts
Labels: ✨ feature, 🔌 api

#47 #34 refactor: React.FC 제거 및 명시적 props 타입으로 변경
  src/app/mypage/page.tsx
  src/app/sample/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/FavoriteButton.tsx
  src/components/common/button/ToggleButton.tsx
Labels: 🐛 bugFix, 🛠️ refactor

#50 #4 design: 공통 레이아웃 css 수정
  public/favicon.ico
  public/images/Banner.png
  public/images/Logo.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/header/index.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/constants/config.ts
  src/styles/globals.css
Labels: 🎨 design

#48 #19 채팅창 모달 UI 구현
  src/app/sample/page.tsx
  src/components/chats/ChatBubble.tsx
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatRoomCard.tsx
  src/components/chats/ChatRooms.tsx
  src/components/common/button/FloatingButton.tsx
  src/components/common/button/constants.ts
  src/components/common/modal/ChatModal.tsx
  src/hooks/useClickOutside.ts
  src/styles/globals.css
  src/types/chat.ts
Labels: ✨ feature, 🎨 design

#56 #51 feat: 헤더 메뉴 모달창 UI 구현
  src/app/sample/page.tsx
  src/components/common/modal/ChatModal.tsx
  src/components/common/modal/MenuModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/constants.ts
  src/components/layouts/Header.tsx
  src/constants/config.ts
  src/store/useNotification.ts
  src/types/user.ts
  tailwind.config.ts
Labels: ✨ feature, 🎨 design

#59 #51 feat: confirmModal 공통 컴포넌트 생성
  src/components/common/button/constants.ts
  src/components/common/modal/ConfirmModal.tsx
Labels: ✨ feature, 🎨 design

#61 #51 feat: 헤더 메뉴 알림창 UI 구현
  src/app/page.tsx
  src/components/chats/ChatBubble.tsx
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatMessages.tsx
  src/components/chats/ChatRoomCard.tsx
  src/components/chats/ChatRooms.tsx
  src/components/common/AlarmBedge.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/FloatingButton.tsx
  src/components/common/button/constants.ts
  src/components/common/card/CardShell.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/constants.ts
  src/components/layouts/Header.tsx
  src/components/layouts/Menu.tsx
  src/components/notifications/NotificationCard.tsx
  src/components/notifications/Notifications.tsx
  src/constants/config.ts
  src/types/modal.ts
Labels: ✨ feature, 🎨 design

#62 #60 feat: 관심목록 페이지 UI 구현
  src/app/mypage/wishlist/page.tsx
  src/components/mypage/MyMoimBox.tsx
  src/components/mypage/MyMoimCard.tsx
  src/types/moim.ts
Labels: ✨ feature, 🎨 design

#68 #20 feat: 마이페이지 내정보 목업 데이터 적용
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/mypage/MypageSidebar.tsx
  src/constants/config.ts
  src/mockup/user.json
Labels: 🐛 bugFix

#74 #72 feat: 채팅 모달 창 전환을 위한 전역상태값 추가
  src/app/ClientLayout.tsx
  src/components/chats/ChatMessages.tsx
  src/components/chats/ChatRooms.tsx
  src/components/common/card/CardShell.tsx
  src/mockup/chat.js
  src/mockup/messages.js
  src/store/useChatStore.ts
Labels: ✨ feature, 🎨 design

#75 #51 fix: 헤더 메뉴 모달창 내 아이콘 클릭 시 창 닫힘 처리
  src/components/common/AlarmBedge.tsx
  src/components/common/card/CardShell.tsx
  src/components/common/modal/constants.ts
  src/components/layouts/Header.tsx
  src/components/layouts/Menu.tsx
  src/components/notifications/NotificationCard.tsx
  src/components/notifications/Notifications.tsx
  src/constants/config.ts
  src/mockup/nofitication.js
  src/store/useNotificationStore.ts
Labels: 🐛 bugFix

#76 #60 fix: 관심/참여 모임 목록 타입 에러 수정
  src/app/join/page.tsx
  src/app/mypage/wishlist/page.tsx
  src/components/mypage/MyMoimCard.tsx
Labels: 🐛 bugFix

#78 #60 fix: 모임 리스트 타입 정의 파일 경로 변경 건 적용
  src/components/chats/ChatRooms.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/constants.ts
  src/components/mypage/MyMoimCard.tsx
Labels: 🐛 bugFix, 🎨 design

#80 #60 feat: 모임 리스트 나가기 버튼에 컨펌 모달 연결
  src/app/ClientLayout.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/mypage/MyMoimCard.tsx
  src/store/useModalStore.ts
Labels: ✨ feature

#82 #81 chore: react-query 설치 및 provider 설정
  package-lock.json
  package.json
  src/app/layout.tsx
  src/providers/index.tsx
  src/providers/type.ts
Labels: ♻️ chore

#92 #4 design: 헤더 종속 모달 컴포넌트 위치 수정
  src/components/common/modal/Modal.tsx
  src/components/common/modal/constants.ts
  src/components/layouts/Header.tsx
Labels: 🎨 design

#91 #81 feat: API 요청 관련 공통 유틸 생성
  src/api/fetchClient.ts
  src/api/functions/chatAPI.ts
  src/api/options/chatOption.ts
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatMessages.tsx
  src/components/chats/ChatRoomCard.tsx
  src/components/chats/ChatRooms.tsx
  src/mockup/chat.js
  src/mockup/messages.js
  src/types/chat.ts
Labels: ✨ feature, 🔌 api

#95 #20 design: 마이페이지 내정보 css 수정
  src/app/mypage/MyPage.tsx
  src/app/mypage/page.tsx
  src/components/mypage/MyMoimBox.tsx
  src/mockup/user.json
Labels: 🎨 design

#101 #81 feat: 채팅 삭제 API 로직 추가
  src/api/fetchClient.ts
  src/api/functions/chatAPI.ts
  src/api/options/chatOption.ts
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatMessages.tsx
Labels: 🐛 bugFix, ✨ feature, 🔌 api

#106 #81 feat: 채팅 일대일 채팅방 생성 API 추가
  src/api/functions/chatAPI.ts
  src/api/options/chatOption.ts
  src/app/ClientLayout.tsx
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatMessages.tsx
  src/components/chats/ChatRoomCard.tsx
  src/components/chats/ChatRooms.tsx
  src/components/common/card/CardShell.tsx
  src/components/common/modal/Modal.tsx
  src/store/useChatStore.ts
  src/types/chat.ts
Labels: ✨ feature, 🛠️ refactor, 🔌 api

#114 #87 design: 마이페이지 전체 레이아웃 반응형 css 수정
  src/app/join/page.tsx
  src/app/mypage/layout.tsx
  src/components/mypage/MypageSidebar.tsx
Labels: 🎨 design

#113 #90 feat: 읽지 않은 알림만 필터링 기능 추가
  src/api/options/notificationOption.ts
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatRooms.tsx
  src/components/common/card/CardShell.tsx
  src/components/common/loadingSpinner/LoadingSpinner.tsx
  src/components/common/modal/constants.ts
  src/components/notifications/Notifications.tsx
Labels: ✨ feature, 🛠️ refactor, 🎨 design

#117 #115 feat: 웹소켓 통신 데이터 타입 수정
  src/components/chats/ChatMessages.tsx
  src/components/chats/ChatRooms.tsx
Labels: 🐛 bugFix, ✨ feature

#121 #93 feat: 모임 참여자 조회 모달 컴포넌트 추가
  src/api/functions/myMoimAPI.ts
  src/api/options/chatOption.ts
  src/api/options/notificationOption.ts
  src/app/ClientLayout.tsx
  src/app/join/JoinPage.tsx
  src/app/mypage/likelist/LikePage.tsx
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatRoomCard.tsx
  src/components/common/button/FavoriteButton.tsx
  src/components/common/card/PeopleCard.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/common/modal/DetailModal.tsx
  src/components/layouts/Header.tsx
  src/components/mypage/MyMoimCard.tsx
  src/store/useModalStore.ts
  src/types/mymoim.ts
Labels: ✨ feature, 🛠️ refactor, 🔌 api

#122 #93 fix: 모임 나가기 성공 시 모달 close 이벤트 추가
  src/api/options/myMoimOption.ts
  src/app/mypage/likelist/LikePage.tsx
  src/components/mypage/MyMoimCard.tsx
  src/types/mymoim.ts
Labels: 🐛 bugFix

#127 #115 fix: map 키 중복 관련 에러 수정
  src/components/chats/ChatMessage.tsx
  src/components/chats/ChatMessages.tsx
Labels: 🐛 bugFix

#128 #93 fix: 다른 사람 정보 페이지 라우팅 경로 수정
  src/api/options/myMoimOption.ts
  src/components/common/card/PeopleCard.tsx
  src/components/mypage/MyMoimCard.tsx
Labels: 🐛 bugFix

#131 #100 fix: ISO 타임존 관련 오차 보정을 위한 유틸 함수 생성
  src/components/mypage/schedule/date.ts
  src/components/mypage/schedule/index.tsx
  src/styles/schedule.css
  src/types/schedule.ts
Labels: 🐛 bugFix, ✨ feature, 🛠️ refactor

#135 #132 feat: 전체 페이지 UI/UX 개선 작업
  src/app/join/page.tsx
  src/app/mypage/joinlist/JoinPage.tsx
  src/app/mypage/joinlist/page.tsx
  src/app/mypage/likelist/LikePage.tsx
  src/components/common/card/PeopleCard.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/layouts/Header.tsx
  src/components/moim/moimdetail/index.tsx
  src/components/mypage/MyMoimCard.tsx
  src/constants/config.ts
  src/store/useModalStore.ts
Labels: 🐛 bugFix, ✨ feature, 🛠️ refactor, 🎨 design

#139 #132 feat: 미들웨어를 이용한 로그인 접근 제한 기능 추가
  public/images/UserProfile.png
  src/components/chats/ChatRoomCard.tsx
  src/components/common/card/PeopleCard.tsx
  src/components/mypage/MyMoimCard.tsx
  src/components/mypage/sidebar/MypageSidebar.tsx
  src/middleware.ts
  src/store/useAuthStore.ts
  src/store/useModalStore.ts
Labels: 🐛 bugFix, ✨ feature

#148 #132 fix: 정보 수정 페이지 이미지 초기화되는 버그 해결
  src/components/moim/moimcarditem/index.tsx
  src/components/moim/moimdetail/index.tsx
  src/components/moim/moimrolestatus/index.tsx
  src/components/mypage/MyMoimCard.tsx
  src/components/mypage/edit/index.tsx
  src/components/mypage/schedule/index.tsx
Labels: 🐛 bugFix, 🎨 design

#151 #132 fix: 드롭다운 z-index 수정
  src/components/common/card/PeopleCard.tsx
  src/components/common/input/Dropdown.tsx
  src/components/common/modal/constants.ts
  src/components/moim/moimdetail/index.tsx
  src/components/moim/moimeditform/index.tsx
  src/components/moim/moimform/index.tsx
  src/components/moim/moimmember/index.tsx
  src/types/moim.ts
Labels: 🐛 bugFix, 🎨 design
